  proxy:
    container_name: proxy
    image: traefik:v2.9
    command:
      - "--accesslog"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.file.directory=/configuration/"
      - "--providers.file.watch=true"
    ports:
      - ${TRAEFIC_PORT_HTTP:-80}:80
    # env_file:
      # - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.proxy.entrypoints=web"
      - "traefik.http.routers.proxy.rule=Host(`proxy.localhost`)"
      - "traefik.http.services.proxy.loadbalancer.server.port=8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - local-network
    logging:
      driver: none
